name: management_system
description: "A Management System."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.0.0  
  crypto: ^3.0.3
  sqflite_common_ffi: ^2.3.6
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  file_picker: ^10.2.0
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
